### ISSUE TITLE
change_ordering flag not working on a VGG19 pre-trained model

### ISSUE THREAD

**Issue by lucasrla** [nerox8664/onnx2keras#20]
I am trying to convert a pre-trained VGG19 model from ONNX to Keras and then run it on my CPU (run = just predict, not train).

I managed to convert it with `onnx2keras` but then ran into issues with  NCHW `channel_first` `(3, 224, 224)` v. NHWC `channel_last` `(224, 224, 3)`. Here is the error I get when running the converted model with Keras (TensorFlow backend):

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
```

I went back to `onnx2keras` and realized there is an experimental flag `change_ordering` that seems to do what I needed!

Unfortunately, `change_ordering` does not seem to work with my model: 

```
ValueError: Operands could not be broadcast together with shapes (224, 224, 3) (3, 224, 224)
```

Here is the full stack trace:

```
ValueError                                Traceback (most recent call last)
<ipython-input-1-3a0e0ae82f31> in <module>()
      8 
      9 
---> 10 keras_m = onnx_to_keras(onnx_m, ['input'], verbose=True, change_ordering=True)

~/Documents/dev/venv/lib/python3.7/site-packages/onnx2keras/converter.py in onnx_to_keras(onnx_model, input_names, input_shapes, name_policy, verbose, change_ordering)
    212
    213 
--> 214         model_tf_ordering = keras.models.Model.from_config(conf)
    215 
    216         for dst_layer, src_layer in zip(model_tf_ordering.layers,

~/Documents/dev/venv/lib/python3.7/site-packages/keras/engine/network.py in from_config(cls, config, custom_objects)
   1030                 if layer in unprocessed_nodes:
   1031                     for node_data in unprocessed_nodes.pop(layer):
-> 1032                         process_node(layer, node_data)
   1033 
   1034         name = config.get('name')

~/Documents/dev/venv/lib/python3.7/site-packages/keras/engine/network.py in process_node(layer, node_data)
    989             # and building the layer if needed.
    990             if input_tensors:
--> 991                 layer(unpack_singleton(input_tensors), **kwargs)
    992 
    993         def process_layer(layer_data):

~/Documents/dev/venv/lib/python3.7/site-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    429                                          'You can build it manually via: '
    430                                          '`layer.build(batch_input_shape)`')
--> 431                 self.build(unpack_singleton(input_shapes))
    432                 self.built = True
    433 

~/Documents/dev/venv/lib/python3.7/site-packages/keras/layers/merge.py in build(self, input_shape)
    254 
    255     def build(self, input_shape):
--> 256         super(Subtract, self).build(input_shape)
    257         if len(input_shape) != 2:
    258             raise ValueError('A `Subtract` layer should be called '

~/Documents/dev/venv/lib/python3.7/site-packages/keras/layers/merge.py in build(self, input_shape)
     89                 shape = input_shape[i][1:]
     90             output_shape = self._compute_elemwise_op_output_shape(output_shape,
---> 91                                                                   shape)
     92         # If the inputs have different ranks, we have to reshape them
     93         # to make them broadcastable.

~/Documents/dev/venv/lib/python3.7/site-packages/keras/layers/merge.py in _compute_elemwise_op_output_shape(self, shape1, shape2)
     59                     raise ValueError('Operands could not be broadcast '
     60                                      'together with shapes ' +
---> 61                                      str(shape1) + ' ' + str(shape2))
     62                 output_shape.append(i)
     63         return tuple(output_shape)

ValueError: Operands could not be broadcast together with shapes (224, 224, 3) (3, 224, 224)
```

I am using `python3.7` and (all from pip): `onnx==1.5.0`, `onnx2keras==0.0.4`, `Keras==2.2.4`, and `tensorflow==1.14.0`.

Here is the code that gets me the stack trace above (on a Jupyter Notebook):

```
import onnx
from onnx2keras import onnx_to_keras
onnx_m = onnx.load('VGG19_PRETRAINED.onnx')
keras_m = onnx_to_keras(onnx_m, ['input'], verbose=True, change_ordering=True)
```

@nerox8664, thanks a lot for this (very useful!) library. I do appreciate any hints you might have about my issue.

**Comment by nerox8664** [comment]
Hello @lucasrla.

I fixed several problems related to `flatten` and `reshape` layers.  Please, upgrade library to the latest version: using `pip install --upgrade onnx2keras`.

Here is how to reproduce VGG19 conversion [my snippet](https://gist.github.com/nerox8664/a6f6e9504328ad8a3d14c786f625312e)

Also please check if the model input has proper shape (NHWC after `change_ordering`).

**Comment by lucasrla** [comment]
I really appreciate your quick response and the effort to update the library, @nerox8664.

I upgraded onnx2keras to 0.0.5 via pip and tried to reproduce your `torch`-based snippet (both on Jupyter and via command line). Unfortunately, I am now getting an `AttributeError`:

```
AttributeError: 'tuple' object has no attribute 'layer'
```

In fact, I also get the exact same error when I tried to re-run my previous code:

```
import onnx
from onnx2keras import onnx_to_keras
onnx_m = onnx.load('VGG19_PRETRAINED.onnx')
keras_m = onnx_to_keras(onnx_m, ['input'], verbose=True, change_ordering=True)
```

Please find in [this gist](https://gist.github.com/lucasrla/3cd105c9e73a825463aeecfcfdebd6f2) the full stack trace that I got from executing your snippet.

Do you have any ideas about what might be happening? Am I missing something obvious?

Besides the libraries I mentioned before, I am on macOS with no GPU. And just a bit more context for you, my .onnx file is a VGG19 model that was "repurposed" with MATLAB and then converted to ONNX.

Thank you again.

**Comment by nerox8664** [comment]
Hello.

I tested the snippet with TF 1.13 version, so with 1.14 I can reproduce your problem (in fact, the problem with `tf.contrib.layers.flatten` layer.

Please, fetch `onnx2keras==0.0.6` and try again.

**Comment by lucasrla** [comment]
I just upgraded `onnx2keras` to `0.0.6` but I am still getting the same error:

```
AttributeError: 'tuple' object has no attribute 'layer'
```

With `0.0.5` the stack trace pointed to `line 224` of `onnx2keras/reshape_layers.py`:

```
  File "~/Documents/dev/venv/lib/python3.7/site-packages/onnx2keras/reshape_layers.py", line 224, in convert_flatten
    layers[node_name] = lambda_layer(input_0)
```

Given your latest commit, it now refers to `line 220` [[link]](https://github.com/nerox8664/onnx2keras/blob/d440ef8b35ef4ab8deed16a45db2accbed792e53/onnx2keras/reshape_layers.py#L220) within `convert_flatten()`:

```
  File "~/Documents/dev/venv/lib/python3.7/site-packages/onnx2keras/reshape_layers.py", line 220, in convert_flatten
    layers[node_name] = lambda_layer(input_0)
```

From what I can grasp of your [latest commit](https://github.com/nerox8664/onnx2keras/commit/d440ef8b35ef4ab8deed16a45db2accbed792e53), you modified `convert_reshape()` only. Maybe `convert_flatten()` also needs some change?

Thanks once more!

**Comment by nerox8664** [comment]
Try once again please, I changed `convert_flatten` as well.

**Comment by lucasrla** [comment]
I just upgraded to `0.0.7`. Thank you.

When running your snippet I got stuck on another error. Please find below the last lines from my stack trace. 

It seems that keras (my version is `2.2.4`) was expecting a string (either `'channels_first'` or `'channels_last'`) but instead got a tensor.

```
DEBUG:onnx2keras:######
DEBUG:onnx2keras:...
DEBUG:onnx2keras:Converting ONNX operation
DEBUG:onnx2keras:type: Flatten
DEBUG:onnx2keras:node_name: 77
DEBUG:onnx2keras:node_params: {'axis': 1, 'change_ordering': True, 'name_policy': 'short'}
DEBUG:onnx2keras:...
DEBUG:onnx2keras:Check if all inputs are available:
DEBUG:onnx2keras:Check input 0 (name 76).
DEBUG:onnx2keras:... found all, continue
DEBUG:onnx2keras:flatten:Convert inputs to Keras/TF layers if needed.
Traceback (most recent call last):
  File "test_onnx_torch.py", line 29, in <module>
    k_model = onnx_to_keras(onnx_model, ['input'], name_policy='short', change_ordering=True)
  File "~/Documents/dev/venv/lib/python3.7/site-packages/onnx2keras/converter.py", line 170, in onnx_to_keras
    keras_names
  File "~/Documents/dev/venv/lib/python3.7/site-packages/onnx2keras/reshape_layers.py", line 223, in convert_flatten
    layers[node_name] = keras.layers.Flatten(layers[node_name])
  File "~/Documents/dev/venv/lib/python3.7/site-packages/keras/layers/core.py", line 494, in __init__
    self.data_format = K.normalize_data_format(data_format)
  File "~/Documents/dev/venv/lib/python3.7/site-packages/keras/backend/common.py", line 173, in normalize_data_format
    data_format = value.lower()
AttributeError: 'Tensor' object has no attribute 'lower'
```

Thanks!

**Comment by nerox8664** [comment]
Try `0.0.8`, please. There was an error with layer creation.

**Comment by lucasrla** [comment]
Great! `0.0.8` worked seamlessly with your snippet. 

For the record, here is the output I got from your `print('Error: {0}'.format(error))`

```
Error: 2.5390181690454483e-07
```

Unfortunately, when trying to convert my VGG19 model with the `change_ordering` flag on, I am still getting the same `ValueError` exception that I first referred to. [The stack trace is the same as in my first comment](https://github.com/nerox8664/onnx2keras/issues/20#issue-500346498) and it ends with:

``` 
ValueError: Operands could not be broadcast together with shapes (224, 224, 3) (3, 224, 224)
```

The conversion seems just fine when `change_ordering` is off.

If you are willing to try with my model, I have just uploaded the `pretrained_VGG19.onnx` file to Firefox Send – [here is the link](https://send.firefox.com/download/9bdd837d996674e0/#oDbTIY87vpqPqj-imuV-Kw). 

In any case, if you have any other hints or new ideas, please do let me know. Thank you again!

**Comment by nerox8664** [comment]
The model contains constants (e.g. for input normalization) which were not permuted well.
Now the converter (`0.0.9`) is able to permute constant shapes, and finally I'm able to convert your ONNX model.

[Snippet](https://gist.github.com/nerox8664/370ac8e2b7da2d122ba97dab256eba1f)

**Comment by lucasrla** [comment]
Thank you so much, Grigory. It is now working perfectly.
